### ISSUE TITLE
error message from ucglib when trying to compile code

### ISSUE THREAD

**Issue by daniu-de** [ElektorLabs/170112-3-displays-alarm-clock-with-TFT-screen#3]
Hi,
can you tell me which version of ucglib you used. I can't get the code to compile - with this error:

`In file included from /*/Ucglib/Ucglib.h:61:0,
                 from Wecker_Original_ino.ino:22:
/*/Ucglib/ucg.h:120:25: internal compiler error: in type_hash_canon, at tree.c:6953
 typedef uint8_t PROGMEM ucg_pgm_uint8_t;`

I use a raspberry Pi and connect the 328P on the board with a self made 6pin ISP connector. On the Raspberry I use the ide: 2.1.0.5. Installed all libraries manually. Tried several ucglib version but keep getting an error message.

Would appreciate help with this

regards

**Comment by lab-mathias-claussen** [comment]
Hi daniu-de,

we used the 1.5.2 version for the library with an older ArduinoIDE version. The errors seems to be somewhat starnge and may be realted to compiler changes done in the last 17 months. We will try to check if the code still compiles with current tools

**Comment by daniu-de** [comment]
Hi
Thanks for your answer. In the meantime I tried a newer version of arduino ide (raspberry repository does only have rather old versions) which made the code compile nicely.
Now I only got the problem of getting the 12Mhz to work (is it possible that the explanation you give on how to do this does not work anymore? Was it ever possible to achieve this without a new bootloader?) and ... that I don't get to run this newer version of arduino ide on the raspberry pi directly. So I have to transfer hex files from a normal pc to the raspberry as I don't have a programmer for the pc. 
Regards

**Comment by lab-mathias-claussen** [comment]
Hi daniu-de,

please have a look at: https://www.elektormagazine.com/labs/3-displays-alarm-clock-with-tft-screen-softwareupdate-170112-b . We added a Board with 12MHz to the arduino IDE so the F_CPU define is set correctly. For the Bootloader, we haven't used one for the final project but moved code with an ISP programmer to the 328p.

**Comment by daniu-de** [comment]
Thanks for that info. Good for testing but in the end I definitely want to adjust the software according to my liking

**Comment by lab-mathias-claussen** [comment]
As the reason for this Issue is no longer valid, we will close the issue here.
